In [166]:
from __future__ import print_function
%matplotlib inline
import warnings
warnings.filterwarnings('ignore')
import os
os.environ["CUDA_VISIBLE_DEVICES"] = "4,5"
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import torchvision
from torchvision import datasets, transforms
import matplotlib.pyplot as plt
import numpy as np
from PIL import Image
from tqdm.notebook import tqdm
from six.moves import urllib

torch.manual_seed(0)
plt.ion()  

In [167]:
opener = urllib.request.build_opener()
opener.addheaders = [('User-agent', 'Mozilla/5.0')]
urllib.request.install_opener(opener)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
device = torch.device("cpu")

full_dataset = torchvision.datasets.ImageFolder(root = '/data/siddhant/MedicalSTN/DrVineetData/Knee_AP', 
                                     transform=transforms.Compose([
                       transforms.ToTensor(),
                       transforms.Resize((512,512)),
#                         transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
                   ]))
train_size = int(0.8 * len(full_dataset))
test_size = len(full_dataset) - train_size
train_dataset, test_dataset = torch.utils.data.random_split(full_dataset, [train_size, test_size])

# Training dataset
train_loader = torch.utils.data.DataLoader(
    train_dataset, 
    batch_size=64, shuffle=True, num_workers=2)
# Test dataset
#TODO find a better test/train split
test_loader = torch.utils.data.DataLoader(
    test_dataset, 
    batch_size=64, shuffle=True, num_workers=2)

In [193]:
class STNresnet(nn.Module):
    def __init__(self):
        super(STNresnet, self).__init__()
        # Spatial transformer localization-network
        self.finalfc = nn.Linear(1000, 10)
        self.localization = nn.Sequential(
            nn.Conv2d(3, 8, kernel_size=7),
            nn.MaxPool2d(2, stride=2),
            nn.ReLU(True),
            nn.Conv2d(8, 10, kernel_size=5),
            nn.MaxPool2d(2, stride=2),
            nn.ReLU(True)
        )

        # Regressor for the 3 * 2 affine matrix
        self.fc_loc = nn.Sequential(
            nn.Linear(10 * 124 * 124, 32),
            nn.ReLU(True),
            nn.Linear(32, 3 * 2)
        )

        # Initialize the weights/bias with identity transformation
        self.fc_loc[2].weight.data.zero_()
        self.fc_loc[2].bias.data.copy_(torch.tensor([1, 0, 0, 0, 1, 0], dtype=torch.float))
        self.resnetportion = torchvision.models.resnet18(pretrained = False)
    
    def stn(self, x):
        xs = self.localization(x)
        xs = xs.view(x.shape[0], -1) 
        theta = self.fc_loc(xs)
        theta = theta.view(-1, 2, 3)

        grid = F.affine_grid(theta, x.size())
        x = F.grid_sample(x, grid)

        return x
    
    def forward(self, x):
        xs = self.localization(x)
        xs = xs.view(x.shape[0], -1) 
        theta = self.fc_loc(xs)
        theta = theta.view(-1, 2, 3)

        grid = F.affine_grid(theta, x.size())
        x = F.grid_sample(x, grid)
        x = self.resnetportion(x)
        x = self.finalfc(x)
        return F.log_softmax(x, dim=1)


In [194]:
class STNnet(nn.Module):
    def __init__(self):
        super(STNnet, self).__init__()
        self.conv1 = nn.Conv2d(3, 10, kernel_size=5)
        self.conv2 = nn.Conv2d(10, 20, kernel_size=5)
        self.conv2_drop = nn.Dropout2d()
        self.fc1 = nn.Linear(20 * 125 * 125, 50)
        self.fc2 = nn.Linear(50, 10)

        # Spatial transformer localization-network
        self.localization = nn.Sequential(
            nn.Conv2d(3, 8, kernel_size=7),
            nn.MaxPool2d(2, stride=2),
            nn.ReLU(True),
            nn.Conv2d(8, 10, kernel_size=5),
            nn.MaxPool2d(2, stride=2),
            nn.ReLU(True)
        )

        # Regressor for the 3 * 2 affine matrix
        self.fc_loc = nn.Sequential(
            nn.Linear(10 * 124 * 124, 32),
            nn.ReLU(True),
            nn.Linear(32, 3 * 2)
        )

        # Initialize the weights/bias with identity transformation
        self.fc_loc[2].weight.data.zero_()
        self.fc_loc[2].bias.data.copy_(torch.tensor([1, 0, 0, 0, 1, 0], dtype=torch.float))

    # Spatial transformer network forward function
    def stn(self, x):
        xs = self.localization(x)
        xs = xs.view(x.shape[0], -1) 
        theta = self.fc_loc(xs)
        theta = theta.view(-1, 2, 3)

        grid = F.affine_grid(theta, x.size())
        x = F.grid_sample(x, grid)

        return x

    def forward(self, x):
        x = self.stn(x)
        x = F.relu(F.max_pool2d(self.conv1(x), 2))
        x = F.relu(F.max_pool2d(self.conv2_drop(self.conv2(x)), 2))
        x = x.view(x.shape[0], -1)
        x = F.relu(self.fc1(x))
        x = F.dropout(x, training=self.training)
        x = self.fc2(x)
        return F.log_softmax(x, dim=1)

In [195]:
# model = STNnet().to(device)
model = STNresnet().to(device)
optimizer = optim.SGD(model.parameters(), lr=0.01)

In [196]:
def train(epoch):
    model.train()
    for data, target in tqdm(train_loader): 
        data, target = data.to(device), target.to(device)

        optimizer.zero_grad()
        output = model(data)
        loss = F.nll_loss(output, target)
        loss.backward()
        optimizer.step()
#         if batch_idx % 5 == 0:
#             print('Train Epoch: {} [{}/{} ({:.0f}%)]\tLoss: {:.6f}'.format(
#                 epoch, batch_idx * len(data), len(train_loader.dataset),
#                 100. * batch_idx / len(train_loader), loss.item()))


def test():
    with torch.no_grad():
        model.eval()
        test_loss = 0
        correct = 0
        preds = []
        targets = []
        for data, target in tqdm(test_loader):
            data, target = data.to(device), target.to(device)
            output = model(data)

            # sum up batch loss
            test_loss += F.nll_loss(output, target, size_average=False).item()
            # get the index of the max log-probability
#             print(output)
            pred = output.max(1, keepdim=True)[1]
            # print(pred)
            correct += pred.eq(target.view_as(pred)).sum().item()
            preds.extend(np.array(pred.cpu()))
            targets.extend(np.array(target.cpu()))
        from sklearn.metrics import confusion_matrix
        conf_mat=confusion_matrix(targets, preds)
        print(conf_mat)
        #TODO make confusion matrix
        test_loss /= len(test_loader.dataset)
        print('\nTest set: Average loss: {:.4f}, Accuracy: {}/{} ({:.0f}%)\n'
              .format(test_loss, correct, len(test_loader.dataset),
                      100. * correct / len(test_loader.dataset)))

def train_conf():
    with torch.no_grad():
        model.eval()
        train_loss = 0
        correct = 0
        preds = []
        targets = []
        for data, target in tqdm(train_loader):
            data, target = data.to(device), target.to(device)
            output = model(data)
            # sum up batch loss
            train_loss += F.nll_loss(output, target, size_average=False).item()
            # get the index of the max log-probability
            pred = output.max(1, keepdim=True)[1]
            # print(pred)
            correct += pred.eq(target.view_as(pred)).sum().item()
            preds.extend(np.array(pred.cpu()))
            targets.extend(np.array(target.cpu()))
        from sklearn.metrics import confusion_matrix
        conf_mat=confusion_matrix(targets, preds)
        print(conf_mat)
        train_loss /= len(train_loader.dataset)
        print('\nTrain set: Average loss: {:.4f}, Accuracy: {}/{} ({:.0f}%)\n'
              .format(train_loss, correct, len(train_loader.dataset),
                      100. * correct / len(train_loader.dataset)))

In [ ]:
def convert_image_np(inp):
    """Convert a Tensor to numpy image."""
    inp = inp.numpy().transpose((1, 2, 0))
    # mean = np.array([0.485, 0.456, 0.406])
    # std = np.array([0.229, 0.224, 0.225])
    # inp = std * inp + mean
    # inp = np.clip(inp, 0, 1)
    return inp

# We want to visualize the output of the spatial transformers layer
# after the training, we visualize a batch of input images and
# the corresponding transformed batch using STN.


def visualize_stn():
    with torch.no_grad():
        # Get a batch of training data
        data = next(iter(test_loader))[0].to(device)

        input_tensor = data.cpu()
        transformed_input_tensor = model.stn(data).cpu()
        print(input_tensor.shape, transformed_input_tensor.shape, max(input_tensor.flatten()), max(transformed_input_tensor.flatten()))
        in_grid = convert_image_np(
            torchvision.utils.make_grid(input_tensor))

        out_grid = convert_image_np(
            torchvision.utils.make_grid(transformed_input_tensor))

        # Plot the results side-by-side
        f, axarr = plt.subplots(1, 2)
        axarr[0].imshow(in_grid)
        axarr[0].set_title('Dataset Images')

        axarr[1].imshow(out_grid)
        axarr[1].set_title('Transformed Images')

for epoch in range(1, 150 + 1):
    train(epoch)
    train_conf()
    test()

# Visualize the STN transformation on some input batch
visualize_stn()

plt.ioff()
plt.show()

  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/8 [00:00<?, ?it/s]

[[  0   0   0  48  29]
 [  0   0   0  63  17]
 [  0   0   0  82   5]
 [  0   0   0 136   0]
 [  0   0   0  90  42]]

Test set: Average loss: 1.9266, Accuracy: 178/512 (35%)



  0%|          | 0/2 [00:00<?, ?it/s]

[[ 0  0  0 19  7]
 [ 0  0  0 17  3]
 [ 0  0  0 14  0]
 [ 0  0  0 31  0]
 [ 0  0  0 22 15]]

Test set: Average loss: 1.9247, Accuracy: 46/128 (36%)



  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/8 [00:00<?, ?it/s]

[[  1   0   1   2  73]
 [  0   0   0   0  80]
 [  0   0   2   1  84]
 [  0   0   0 136   0]
 [  0   0   0  54  78]]

Test set: Average loss: 1.6652, Accuracy: 217/512 (42%)



  0%|          | 0/2 [00:00<?, ?it/s]

[[ 0  0  0  1 25]
 [ 0  0  0  0 20]
 [ 0  0  0  0 14]
 [ 0  0  0 31  0]
 [ 0  0  0 17 20]]

Test set: Average loss: 1.6763, Accuracy: 51/128 (40%)



  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/8 [00:00<?, ?it/s]

[[  0   0   0   2  75]
 [  0   0   0   0  80]
 [  0   0   0   0  87]
 [  0   0   0 136   0]
 [  1   0   0  52  79]]

Test set: Average loss: 1.4501, Accuracy: 215/512 (42%)



  0%|          | 0/2 [00:00<?, ?it/s]

[[ 0  0  0  0 26]
 [ 0  0  0  0 20]
 [ 0  0  0  0 14]
 [ 0  0  0 31  0]
 [ 1  0  0 17 19]]

Test set: Average loss: 1.4638, Accuracy: 50/128 (39%)



  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/8 [00:00<?, ?it/s]

[[ 13   0   0   3  61]
 [  1   0   0   0  79]
 [  0   0   0   7  80]
 [  0   0   0 136   0]
 [  1   0   0  51  80]]

Test set: Average loss: 1.3102, Accuracy: 229/512 (45%)



  0%|          | 0/2 [00:00<?, ?it/s]

[[ 3  0  0  1 22]
 [ 0  0  0  0 20]
 [ 0  0  1  0 13]
 [ 0  0  0 31  0]
 [ 1  0  0 17 19]]

Test set: Average loss: 1.3223, Accuracy: 54/128 (42%)



  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/8 [00:00<?, ?it/s]

[[ 12   5   5   0  55]
 [  1  14   2   0  63]
 [  0   1  13   0  73]
 [  0   0   0 135   1]
 [  1   3   5  51  72]]

Test set: Average loss: 1.1463, Accuracy: 246/512 (48%)



  0%|          | 0/2 [00:00<?, ?it/s]

[[ 3  3  4  0 16]
 [ 0  5  0  0 15]
 [ 0  1  1  0 12]
 [ 0  0  0 31  0]
 [ 1  1  0 17 18]]

Test set: Average loss: 1.1590, Accuracy: 58/128 (45%)



  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/8 [00:00<?, ?it/s]

[[ 30   2  18   0  27]
 [ 11   1   7   0  61]
 [ 11   0  39   0  37]
 [  0   0   0 127   9]
 [ 14   0  15  46  57]]

Test set: Average loss: 1.1451, Accuracy: 254/512 (50%)



  0%|          | 0/2 [00:00<?, ?it/s]

[[12  0  5  0  9]
 [ 6  0  2  0 12]
 [ 0  0  7  0  7]
 [ 0  0  0 29  2]
 [ 3  0  0 17 17]]

Test set: Average loss: 1.1431, Accuracy: 65/128 (51%)



  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/8 [00:00<?, ?it/s]

[[ 41   1  12   0  23]
 [ 20   1   1   0  58]
 [ 17   0  37   0  33]
 [  0   0   0 118  18]
 [ 19   0   8  45  60]]

Test set: Average loss: 1.1261, Accuracy: 257/512 (50%)



  0%|          | 0/2 [00:00<?, ?it/s]

[[11  0  4  0 11]
 [ 7  0  1  0 12]
 [ 3  0  5  0  6]
 [ 0  0  0 30  1]
 [ 4  0  0 17 16]]

Test set: Average loss: 1.1026, Accuracy: 62/128 (48%)



  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/8 [00:00<?, ?it/s]

[[ 19   9   3   0  46]
 [  0  47   0   0  33]
 [  1   0  17   0  69]
 [  0   0   0 136   0]
 [  2  10   2  49  69]]

Test set: Average loss: 0.9968, Accuracy: 288/512 (56%)



  0%|          | 0/2 [00:00<?, ?it/s]

[[ 5  2  0  0 19]
 [ 1  7  0  0 12]
 [ 0  0  3  0 11]
 [ 0  0  0 30  1]
 [ 1  2  0 17 17]]

Test set: Average loss: 1.0488, Accuracy: 62/128 (48%)



  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/8 [00:00<?, ?it/s]

[[69  1  2  0  5]
 [44  8  0  0 28]
 [63  0 18  0  6]
 [ 4  0  0 40 92]
 [32  3  4 20 73]]

Test set: Average loss: 1.1584, Accuracy: 208/512 (41%)



  0%|          | 0/2 [00:00<?, ?it/s]

[[23  0  0  0  3]
 [11  0  0  0  9]
 [ 9  0  4  0  1]
 [ 1  0  0 10 20]
 [ 7  1  0  7 22]]

Test set: Average loss: 1.0784, Accuracy: 59/128 (46%)



  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/8 [00:00<?, ?it/s]

[[ 24  10  18   0  25]
 [  3  32   9   0  36]
 [  7   0  60   0  20]
 [  0   0   0 120  16]
 [  8   4  17  44  59]]

Test set: Average loss: 0.9699, Accuracy: 295/512 (58%)



  0%|          | 0/2 [00:00<?, ?it/s]

[[ 8  2  8  0  8]
 [ 2  4  3  0 11]
 [ 2  0  8  0  4]
 [ 0  0  0 28  3]
 [ 1  2  1 16 17]]

Test set: Average loss: 0.9955, Accuracy: 65/128 (51%)



  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/8 [00:00<?, ?it/s]

[[ 42   1   0   0  34]
 [ 16  13   0   0  51]
 [  8   0   2   0  77]
 [  0   0   0   1 135]
 [ 11   0   1   1 119]]

Test set: Average loss: 1.1316, Accuracy: 177/512 (35%)



  0%|          | 0/2 [00:00<?, ?it/s]

[[16  0  0  0 10]
 [ 3  2  0  0 15]
 [ 2  0  2  0 10]
 [ 0  0  0  0 31]
 [ 1  0  0  0 36]]

Test set: Average loss: 1.0611, Accuracy: 56/128 (44%)



  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/8 [00:00<?, ?it/s]

[[ 37   1  10   2  27]
 [  7  10   6   0  57]
 [  7   1  32   6  41]
 [  0   0   0 136   0]
 [ 12   3   7  53  57]]

Test set: Average loss: 1.0905, Accuracy: 272/512 (53%)



  0%|          | 0/2 [00:00<?, ?it/s]

[[11  0  5  1  9]
 [ 2  2  2  0 14]
 [ 2  0  3  0  9]
 [ 0  0  0 31  0]
 [ 2  0  0 17 18]]

Test set: Average loss: 1.1170, Accuracy: 65/128 (51%)



  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/8 [00:00<?, ?it/s]

[[56  4  2  0 15]
 [19 19  0  0 42]
 [58  0 14  0 15]
 [ 0  0  0 70 66]
 [19  0  6 28 79]]

Test set: Average loss: 1.0272, Accuracy: 238/512 (46%)



  0%|          | 0/2 [00:00<?, ?it/s]

[[18  1  1  0  6]
 [ 4  3  0  0 13]
 [ 9  0  2  0  3]
 [ 0  0  0 14 17]
 [ 1  0  0 10 26]]

Test set: Average loss: 0.9732, Accuracy: 63/128 (49%)



  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/8 [00:00<?, ?it/s]

[[ 55  10   4   1   7]
 [ 13  59   1   0   7]
 [ 23   9  46   0   9]
 [  0   0   0 135   1]
 [ 17  14  12  49  40]]

Test set: Average loss: 0.8310, Accuracy: 335/512 (65%)



  0%|          | 0/2 [00:00<?, ?it/s]

[[20  2  2  0  2]
 [ 5 14  0  0  1]
 [ 3  1  6  0  4]
 [ 0  0  0 31  0]
 [ 5  3  1 17 11]]

Test set: Average loss: 0.8557, Accuracy: 82/128 (64%)



  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/8 [00:00<?, ?it/s]

[[ 28   8  18   2  21]
 [  3  41   9   0  27]
 [  4   1  64   1  17]
 [  0   0   0 136   0]
 [  8   1  15  51  57]]

Test set: Average loss: 0.8526, Accuracy: 326/512 (64%)



  0%|          | 0/2 [00:00<?, ?it/s]

[[ 6  2 11  0  7]
 [ 1  5  2  0 12]
 [ 2  0  8  0  4]
 [ 0  0  0 31  0]
 [ 2  1  1 17 16]]

Test set: Average loss: 0.9786, Accuracy: 66/128 (52%)



  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/8 [00:00<?, ?it/s]

[[ 25  48   0   1   3]
 [  4  75   0   0   1]
 [  5  70   3   0   9]
 [  0   2   0 119  15]
 [  9  42   3  46  32]]

Test set: Average loss: 1.2483, Accuracy: 254/512 (50%)



  0%|          | 0/2 [00:00<?, ?it/s]

[[ 8 16  1  0  1]
 [ 0 19  0  0  1]
 [ 2 11  1  0  0]
 [ 0  1  0 29  1]
 [ 3  8  0 16 10]]

Test set: Average loss: 1.1057, Accuracy: 67/128 (52%)



  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/8 [00:00<?, ?it/s]

[[ 18   3  19   2  35]
 [  1   4   8   0  67]
 [  0   1  51   1  34]
 [  0   0   0 136   0]
 [  1   1  10  51  69]]

Test set: Average loss: 1.0125, Accuracy: 278/512 (54%)



  0%|          | 0/2 [00:00<?, ?it/s]

[[ 4  1  9  0 12]
 [ 1  1  2  0 16]
 [ 0  0  5  0  9]
 [ 0  0  0 31  0]
 [ 1  0  1 17 18]]

Test set: Average loss: 1.1404, Accuracy: 59/128 (46%)



  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/8 [00:00<?, ?it/s]

[[ 34  26   3   0  14]
 [  4  58   1   0  17]
 [  7  34  10   0  36]
 [  7   1   0   7 121]
 [  9  13   2   3 105]]

Test set: Average loss: 1.2542, Accuracy: 214/512 (42%)



  0%|          | 0/2 [00:00<?, ?it/s]

[[ 8  8  2  0  8]
 [ 2 11  3  0  4]
 [ 2  4  1  0  7]
 [ 1  1  0  0 29]
 [ 1  2  0  1 33]]

Test set: Average loss: 1.1524, Accuracy: 53/128 (41%)



  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/8 [00:00<?, ?it/s]

[[ 50   1   1   0  25]
 [  8   8   0   0  64]
 [ 10   0  14   0  63]
 [  2   0   0  33 101]
 [ 10   0   3  16 103]]

Test set: Average loss: 1.1209, Accuracy: 208/512 (41%)



  0%|          | 0/2 [00:00<?, ?it/s]

[[13  0  0  0 13]
 [ 2  0  0  0 18]
 [ 3  0  1  0 10]
 [ 0  0  0 10 21]
 [ 1  0  0  4 32]]

Test set: Average loss: 1.1367, Accuracy: 56/128 (44%)



  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/8 [00:00<?, ?it/s]

[[ 73   1   0   1   2]
 [ 21  58   0   0   1]
 [ 49   7  20   0  11]
 [  0   0   0 136   0]
 [ 34   9   5  51  33]]

Test set: Average loss: 0.9488, Accuracy: 320/512 (62%)



  0%|          | 0/2 [00:00<?, ?it/s]

[[24  0  1  0  1]
 [ 7 12  0  0  1]
 [ 7  1  2  0  4]
 [ 0  0  0 31  0]
 [ 6  3  0 17 11]]

Test set: Average loss: 0.8939, Accuracy: 80/128 (62%)



  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/8 [00:00<?, ?it/s]

[[ 36   5   9   0  27]
 [  4  48   6   0  22]
 [  4   2  33   0  48]
 [  0   0   0 129   7]
 [  6   3  10  47  66]]

Test set: Average loss: 0.8506, Accuracy: 312/512 (61%)



  0%|          | 0/2 [00:00<?, ?it/s]

[[ 8  3  6  0  9]
 [ 1 10  3  0  6]
 [ 2  0  5  0  7]
 [ 0  0  0 30  1]
 [ 1  1  1 17 17]]

Test set: Average loss: 0.9450, Accuracy: 70/128 (55%)



  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/8 [00:00<?, ?it/s]

[[ 45  14   0   0  18]
 [ 18  29   0   0  33]
 [ 15  12   5   0  55]
 [  2   0   0 120  14]
 [ 11   4   3  44  70]]

Test set: Average loss: 1.0630, Accuracy: 269/512 (53%)



  0%|          | 0/2 [00:00<?, ?it/s]

[[13  2  1  0 10]
 [ 3  7  0  0 10]
 [ 4  1  0  0  9]
 [ 0  0  0 29  2]
 [ 1  0  0 16 20]]

Test set: Average loss: 1.0132, Accuracy: 69/128 (54%)



  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/8 [00:00<?, ?it/s]

[[ 77   0   0   0   0]
 [ 75   0   2   0   3]
 [ 80   0   7   0   0]
 [  0   0   0 134   2]
 [ 67   0   2  50  13]]

Test set: Average loss: 1.6429, Accuracy: 231/512 (45%)



  0%|          | 0/2 [00:00<?, ?it/s]

[[25  0  1  0  0]
 [14  0  3  0  3]
 [13  0  1  0  0]
 [ 0  0  0 31  0]
 [16  0  0 17  4]]

Test set: Average loss: 1.6172, Accuracy: 61/128 (48%)



  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/8 [00:00<?, ?it/s]

[[ 40  33   1   0   3]
 [  5  74   0   0   1]
 [ 12  51  11   0  13]
 [  3   1   0 120  12]
 [ 16  31   3  43  39]]

Test set: Average loss: 1.1978, Accuracy: 284/512 (55%)



  0%|          | 0/2 [00:00<?, ?it/s]

[[15 10  0  0  1]
 [ 3 16  0  0  1]
 [ 3  5  1  0  5]
 [ 1  1  0 28  1]
 [ 4  7  0 16 10]]

Test set: Average loss: 1.0951, Accuracy: 70/128 (55%)



  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/8 [00:00<?, ?it/s]

[[ 31   2  18   2  24]
 [  9  26  10   0  35]
 [  2   0  63   1  21]
 [  0   0   0 136   0]
 [  2   2  14  51  63]]

Test set: Average loss: 0.8272, Accuracy: 319/512 (62%)



  0%|          | 0/2 [00:00<?, ?it/s]

[[ 9  1  8  0  8]
 [ 2  4  0  0 14]
 [ 1  0  8  0  5]
 [ 0  0  0 31  0]
 [ 1  0  1 17 18]]

Test set: Average loss: 0.9582, Accuracy: 70/128 (55%)



  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/8 [00:00<?, ?it/s]

[[ 77   0   0   0   0]
 [ 67  13   0   0   0]
 [ 84   2   0   0   1]
 [ 15   0   0 121   0]
 [ 77   7   0  47   1]]

Test set: Average loss: 3.3059, Accuracy: 212/512 (41%)



  0%|          | 0/2 [00:00<?, ?it/s]

[[26  0  0  0  0]
 [15  5  0  0  0]
 [14  0  0  0  0]
 [ 2  0  0 29  0]
 [20  1  0 16  0]]

Test set: Average loss: 3.0010, Accuracy: 60/128 (47%)



  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/8 [00:00<?, ?it/s]

[[ 66   1   6   2   2]
 [ 22  41   0   0  17]
 [ 42   0  42   0   3]
 [  0   0   0 136   0]
 [ 27   6   7  52  40]]

Test set: Average loss: 0.8368, Accuracy: 325/512 (63%)



  0%|          | 0/2 [00:00<?, ?it/s]

[[23  1  1  0  1]
 [ 8  6  1  0  5]
 [ 8  0  6  0  0]
 [ 0  0  0 31  0]
 [ 5  3  0 17 12]]

Test set: Average loss: 0.8380, Accuracy: 78/128 (61%)



  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/8 [00:00<?, ?it/s]

[[ 66   3   1   2   5]
 [  7  65   0   0   8]
 [ 22   5  32   0  28]
 [  0   0   0 136   0]
 [ 17   9   7  51  48]]

Test set: Average loss: 0.8071, Accuracy: 347/512 (68%)



  0%|          | 0/2 [00:00<?, ?it/s]

[[22  2  1  0  1]
 [ 3 13  0  0  4]
 [ 4  0  3  0  7]
 [ 0  0  0 31  0]
 [ 3  3  0 17 14]]

Test set: Average loss: 0.8179, Accuracy: 83/128 (65%)



  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/8 [00:00<?, ?it/s]

[[ 47   0  20   0  10]
 [ 23  15  15   0  27]
 [  3   0  77   0   7]
 [  0   0   0 136   0]
 [  8   0  17  49  58]]

Test set: Average loss: 0.8089, Accuracy: 333/512 (65%)



  0%|          | 0/2 [00:00<?, ?it/s]

[[13  0  7  0  6]
 [ 5  2  2  0 11]
 [ 1  0 11  0  2]
 [ 0  0  0 31  0]
 [ 2  0  1 17 17]]

Test set: Average loss: 0.9090, Accuracy: 74/128 (58%)



  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/8 [00:00<?, ?it/s]

[[ 57   0   9   0  11]
 [ 16  27   8   0  29]
 [  7   0  73   0   7]
 [  2   0   0 129   5]
 [ 11   0  14  46  61]]

Test set: Average loss: 0.7521, Accuracy: 347/512 (68%)



  0%|          | 0/2 [00:00<?, ?it/s]

[[15  0  6  0  5]
 [ 3  4  3  0 10]
 [ 1  0 13  0  0]
 [ 0  0  0 29  2]
 [ 1  0  1 17 18]]

Test set: Average loss: 0.8769, Accuracy: 79/128 (62%)



  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/8 [00:00<?, ?it/s]

[[ 67   4   1   1   4]
 [ 34  33   0   0  13]
 [ 66   2  15   0   4]
 [  0   0   0 135   1]
 [ 23  10   7  49  43]]

Test set: Average loss: 1.0717, Accuracy: 293/512 (57%)



  0%|          | 0/2 [00:00<?, ?it/s]

[[22  2  1  0  1]
 [11  5  0  0  4]
 [10  1  3  0  0]
 [ 0  0  0 30  1]
 [ 5  2  0 17 13]]

Test set: Average loss: 0.9115, Accuracy: 73/128 (57%)



  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/8 [00:00<?, ?it/s]

[[12  7 29  1 28]
 [ 0 37 16  0 27]
 [ 0  0 60  0 27]
 [ 0  0  0 91 45]
 [ 1  1 19 31 80]]

Test set: Average loss: 0.9684, Accuracy: 280/512 (55%)



  0%|          | 0/2 [00:00<?, ?it/s]

[[ 4  2 11  0  9]
 [ 0  5  4  0 11]
 [ 0  0  8  0  6]
 [ 0  0  0 23  8]
 [ 1  1  2 10 23]]

Test set: Average loss: 1.2194, Accuracy: 63/128 (49%)



  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/8 [00:00<?, ?it/s]

[[ 53  14   2   1   7]
 [  3  72   2   0   3]
 [ 15  12  45   0  15]
 [  2   0   0 134   0]
 [  7  24   9  51  41]]

Test set: Average loss: 0.7582, Accuracy: 345/512 (67%)



  0%|          | 0/2 [00:00<?, ?it/s]

[[15  6  1  0  4]
 [ 2 17  0  0  1]
 [ 3  2  7  0  2]
 [ 0  0  0 31  0]
 [ 1  4  1 17 14]]

Test set: Average loss: 0.8369, Accuracy: 84/128 (66%)



  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/8 [00:00<?, ?it/s]

[[ 25  30  14   1   7]
 [  0  78   0   0   2]
 [  1  16  64   0   6]
 [  1   0   0 106  29]
 [  3  30  11  38  50]]

Test set: Average loss: 0.8176, Accuracy: 323/512 (63%)



  0%|          | 0/2 [00:00<?, ?it/s]

[[ 6 15  3  0  2]
 [ 0 18  0  0  2]
 [ 1  2  7  0  4]
 [ 0  0  0 26  5]
 [ 1  6  0 14 16]]

Test set: Average loss: 0.9097, Accuracy: 73/128 (57%)



  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/8 [00:00<?, ?it/s]

[[ 76   0   1   0   0]
 [ 41  38   0   0   1]
 [ 71   0  16   0   0]
 [  2   0   0 134   0]
 [ 54   8   2  50  18]]

Test set: Average loss: 1.4048, Accuracy: 282/512 (55%)



  0%|          | 0/2 [00:00<?, ?it/s]

[[26  0  0  0  0]
 [10 10  0  0  0]
 [12  0  2  0  0]
 [ 0  0  0 31  0]
 [12  2  0 17  6]]

Test set: Average loss: 1.3552, Accuracy: 75/128 (59%)



  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/8 [00:00<?, ?it/s]

[[ 66   7   2   0   2]
 [ 12  67   0   0   1]
 [ 19  11  57   0   0]
 [  2   0   0 131   3]
 [ 17  20  10  49  36]]

Test set: Average loss: 0.7104, Accuracy: 357/512 (70%)



  0%|          | 0/2 [00:00<?, ?it/s]

[[21  3  0  0  2]
 [ 5 14  1  0  0]
 [ 4  2  6  0  2]
 [ 0  0  0 30  1]
 [ 3  4  1 17 12]]

Test set: Average loss: 0.8428, Accuracy: 83/128 (65%)



  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/8 [00:00<?, ?it/s]

[[ 70   0   4   2   1]
 [ 22  32   9   0  17]
 [ 13   0  61   0  13]
 [  0   0   0 136   0]
 [ 15   0  16  52  49]]

Test set: Average loss: 0.7889, Accuracy: 348/512 (68%)



  0%|          | 0/2 [00:00<?, ?it/s]

[[16  1  6  0  3]
 [ 7  1  7  0  5]
 [ 3  0  8  0  3]
 [ 0  0  0 31  0]
 [ 3  0  1 17 16]]

Test set: Average loss: 1.0087, Accuracy: 72/128 (56%)



  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/8 [00:00<?, ?it/s]

[[ 31   8  22   2  14]
 [  2  50  15   0  13]
 [  0   1  63   0  23]
 [  0   0   0 136   0]
 [  1   5  20  51  55]]

Test set: Average loss: 0.7480, Accuracy: 335/512 (65%)



  0%|          | 0/2 [00:00<?, ?it/s]

[[10  1 10  0  5]
 [ 1  5  4  0 10]
 [ 0  0  9  0  5]
 [ 0  0  0 31  0]
 [ 1  2  1 17 16]]

Test set: Average loss: 0.9792, Accuracy: 71/128 (55%)



  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/8 [00:00<?, ?it/s]

[[ 16  11  23   0  27]
 [  0  49   8   0  23]
 [  0   1  80   0   6]
 [  0   0   3   1 132]
 [  1   1  19   0 111]]

Test set: Average loss: 0.9450, Accuracy: 257/512 (50%)



  0%|          | 0/2 [00:00<?, ?it/s]

[[ 3  4 10  0  9]
 [ 0  8  2  0 10]
 [ 0  0 12  0  2]
 [ 0  0  0  0 31]
 [ 1  0  1  0 35]]

Test set: Average loss: 1.1145, Accuracy: 58/128 (45%)



  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/8 [00:00<?, ?it/s]

[[ 75   0   0   0   2]
 [ 30  21   0   0  29]
 [ 66   0   4   0  17]
 [  2   0   0 122  12]
 [ 27   0   1  40  64]]

Test set: Average loss: 1.2260, Accuracy: 286/512 (56%)



  0%|          | 0/2 [00:00<?, ?it/s]

[[24  0  0  0  2]
 [10  0  1  0  9]
 [11  0  0  0  3]
 [ 0  0  0 28  3]
 [ 5  0  0 16 16]]

Test set: Average loss: 1.2359, Accuracy: 68/128 (53%)



  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/8 [00:00<?, ?it/s]

[[ 71   1   2   1   2]
 [ 19  55   1   0   5]
 [ 31  22  22   0  12]
 [  1   0   0 135   0]
 [ 20  13   3  51  45]]

Test set: Average loss: 0.9897, Accuracy: 328/512 (64%)



  0%|          | 0/2 [00:00<?, ?it/s]

[[19  0  3  0  4]
 [ 4 11  3  0  2]
 [ 5  3  3  0  3]
 [ 0  0  0 31  0]
 [ 4  4  1 17 11]]

Test set: Average loss: 1.0073, Accuracy: 75/128 (59%)



  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/8 [00:00<?, ?it/s]

[[ 77   0   0   0   0]
 [ 80   0   0   0   0]
 [ 87   0   0   0   0]
 [ 24   0   0 112   0]
 [ 80   0   0  41  11]]

Test set: Average loss: 3.6546, Accuracy: 200/512 (39%)



  0%|          | 0/2 [00:00<?, ?it/s]

[[26  0  0  0  0]
 [20  0  0  0  0]
 [13  0  1  0  0]
 [ 4  0  0 27  0]
 [17  0  0 16  4]]

Test set: Average loss: 2.9009, Accuracy: 58/128 (45%)



  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/8 [00:00<?, ?it/s]

[[ 52  12   3   1   9]
 [  1  70   2   0   7]
 [  7  34  33   0  13]
 [  0   0   0 136   0]
 [  8  17   5  51  51]]

Test set: Average loss: 0.8204, Accuracy: 342/512 (67%)



  0%|          | 0/2 [00:00<?, ?it/s]

[[11  6  3  0  6]
 [ 0 15  3  0  2]
 [ 2  3  5  0  4]
 [ 0  0  0 31  0]
 [ 2  4  1 17 13]]

Test set: Average loss: 0.9313, Accuracy: 75/128 (59%)



  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/8 [00:00<?, ?it/s]

[[ 18  21  13   2  23]
 [  0  45   3   0  32]
 [  0   3  75   0   9]
 [  0   0   0 136   0]
 [  1  12  16  52  51]]

Test set: Average loss: 0.7771, Accuracy: 325/512 (63%)



  0%|          | 0/2 [00:00<?, ?it/s]

[[ 5  8  5  0  8]
 [ 0  9  0  0 11]
 [ 0  0 12  0  2]
 [ 0  0  0 31  0]
 [ 1  2  1 17 16]]

Test set: Average loss: 1.0043, Accuracy: 73/128 (57%)



  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/8 [00:00<?, ?it/s]

[[ 64   9   1   2   1]
 [  9  70   0   0   1]
 [ 24  13  42   0   8]
 [  0   0   0 136   0]
 [ 15  23   8  52  34]]

Test set: Average loss: 0.7495, Accuracy: 346/512 (68%)



  0%|          | 0/2 [00:00<?, ?it/s]

[[18  6  1  0  1]
 [ 3 16  0  0  1]
 [ 5  2  6  0  1]
 [ 0  0  0 31  0]
 [ 1  7  0 17 12]]

Test set: Average loss: 0.7614, Accuracy: 83/128 (65%)



  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/8 [00:00<?, ?it/s]

[[ 70   0   2   0   5]
 [ 19  12  25   0  24]
 [ 25   0  34   0  28]
 [  0   0   0 119  17]
 [ 21   3  11  43  54]]

Test set: Average loss: 1.0980, Accuracy: 289/512 (56%)



  0%|          | 0/2 [00:00<?, ?it/s]

[[22  0  1  0  3]
 [ 8  1  3  0  8]
 [ 6  0  4  0  4]
 [ 0  0  0 27  4]
 [ 3  1  3 14 16]]

Test set: Average loss: 1.1580, Accuracy: 70/128 (55%)



  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/8 [00:00<?, ?it/s]

[[ 66   6   0   0   5]
 [ 15  64   0   0   1]
 [ 35   5  27   0  20]
 [ 11   0   0 125   0]
 [ 18  23   3  47  41]]

Test set: Average loss: 0.9550, Accuracy: 323/512 (63%)



  0%|          | 0/2 [00:00<?, ?it/s]

[[20  4  0  0  2]
 [ 3 15  0  0  2]
 [ 6  1  1  0  6]
 [ 2  0  0 29  0]
 [ 5  5  0 16 11]]

Test set: Average loss: 0.9915, Accuracy: 76/128 (59%)



  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/8 [00:00<?, ?it/s]

[[ 75   0   1   1   0]
 [ 32  46   2   0   0]
 [ 27   0  60   0   0]
 [  0   0   0 136   0]
 [ 38   5   7  51  31]]

Test set: Average loss: 0.8080, Accuracy: 348/512 (68%)



  0%|          | 0/2 [00:00<?, ?it/s]

[[24  1  1  0  0]
 [10  7  2  0  1]
 [ 4  0 10  0  0]
 [ 0  0  0 31  0]
 [ 8  1  1 17 10]]

Test set: Average loss: 0.9043, Accuracy: 82/128 (64%)



  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/8 [00:00<?, ?it/s]

[[ 74   0   0   1   2]
 [ 37  35   0   0   8]
 [ 52   0  26   0   9]
 [  0   0   0 136   0]
 [ 24   5   5  52  46]]

Test set: Average loss: 0.9315, Accuracy: 317/512 (62%)



  0%|          | 0/2 [00:00<?, ?it/s]

[[25  0  0  0  1]
 [ 9  6  0  0  5]
 [ 9  0  1  0  4]
 [ 0  0  0 31  0]
 [ 4  2  0 17 14]]

Test set: Average loss: 0.9421, Accuracy: 77/128 (60%)



  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/8 [00:00<?, ?it/s]

[[ 53   9  11   1   3]
 [  2  71   4   0   3]
 [ 11  13  53   0  10]
 [  0   0   0 136   0]
 [ 11  14   9  51  47]]

Test set: Average loss: 0.7358, Accuracy: 360/512 (70%)



  0%|          | 0/2 [00:00<?, ?it/s]

[[16  6  2  0  2]
 [ 3 14  1  0  2]
 [ 4  2  6  0  2]
 [ 0  0  0 31  0]
 [ 3  3  0 17 14]]

Test set: Average loss: 0.8009, Accuracy: 81/128 (63%)



  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/8 [00:00<?, ?it/s]

[[ 44  15   1   1  16]
 [  1  65   0   0  14]
 [  2   3  44   0  38]
 [  0   0   0 136   0]
 [  4   9   4  51  64]]

Test set: Average loss: 0.7412, Accuracy: 353/512 (69%)



  0%|          | 0/2 [00:00<?, ?it/s]

[[ 8  7  1  0 10]
 [ 0 12  0  0  8]
 [ 1  0  7  0  6]
 [ 0  0  0 31  0]
 [ 0  2  0 17 18]]

Test set: Average loss: 0.9914, Accuracy: 76/128 (59%)



  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/8 [00:00<?, ?it/s]

[[ 53   3   6   1  14]
 [  2  65   1   0  12]
 [  2   2  75   0   8]
 [  0   0   0 136   0]
 [  1   7  16  52  56]]

Test set: Average loss: 0.6212, Accuracy: 385/512 (75%)



  0%|          | 0/2 [00:00<?, ?it/s]

[[11  1  7  0  7]
 [ 1 10  1  0  8]
 [ 0  2 11  0  1]
 [ 0  0  0 31  0]
 [ 0  3  1 17 16]]

Test set: Average loss: 0.8451, Accuracy: 79/128 (62%)



  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/8 [00:00<?, ?it/s]

[[ 71   0   4   0   2]
 [  5  71   1   0   3]
 [  6   1  76   0   4]
 [  0   0   0 136   0]
 [  7   8   8  51  58]]

Test set: Average loss: 0.4947, Accuracy: 412/512 (80%)



  0%|          | 0/2 [00:00<?, ?it/s]

[[18  2  3  0  3]
 [ 3 15  1  0  1]
 [ 1  1 11  0  1]
 [ 0  0  0 31  0]
 [ 2  3  1 17 14]]

Test set: Average loss: 0.7294, Accuracy: 89/128 (70%)



  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/8 [00:00<?, ?it/s]

[[ 77   0   0   0   0]
 [ 64  16   0   0   0]
 [ 74   0  11   0   2]
 [ 18   0   0 118   0]
 [ 62   5   2  44  19]]

Test set: Average loss: 1.9138, Accuracy: 241/512 (47%)



  0%|          | 0/2 [00:00<?, ?it/s]

[[26  0  0  0  0]
 [14  5  0  0  1]
 [12  0  1  0  1]
 [ 3  0  0 28  0]
 [10  2  0 16  9]]

Test set: Average loss: 1.5944, Accuracy: 69/128 (54%)



  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/8 [00:00<?, ?it/s]

[[ 74   0   0   0   3]
 [ 13  65   0   0   2]
 [ 31  21  24   0  11]
 [ 12   0   0 124   0]
 [ 32  14   3  47  36]]

Test set: Average loss: 1.2718, Accuracy: 323/512 (63%)



  0%|          | 0/2 [00:00<?, ?it/s]

[[24  1  0  0  1]
 [ 4 15  0  0  1]
 [ 6  2  3  0  3]
 [ 1  0  0 30  0]
 [ 7  3  1 17  9]]

Test set: Average loss: 1.2242, Accuracy: 81/128 (63%)



  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/8 [00:00<?, ?it/s]

[[ 27  36   3   1  10]
 [  0  76   1   0   3]
 [  0  50  37   0   0]
 [  3   0   0 133   0]
 [  2  32   8  49  41]]

Test set: Average loss: 1.0032, Accuracy: 314/512 (61%)



  0%|          | 0/2 [00:00<?, ?it/s]

[[ 6 13  3  0  4]
 [ 0 17  2  0  1]
 [ 1  6  6  0  1]
 [ 0  0  0 31  0]
 [ 1  8  1 17 10]]

Test set: Average loss: 1.0987, Accuracy: 70/128 (55%)



  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/8 [00:00<?, ?it/s]

[[ 76   0   1   0   0]
 [ 58   4  12   0   6]
 [ 44   0  43   0   0]
 [  2   0   0 130   4]
 [ 51   0   8  48  25]]

Test set: Average loss: 1.4956, Accuracy: 278/512 (54%)



  0%|          | 0/2 [00:00<?, ?it/s]

[[25  0  1  0  0]
 [13  0  4  0  3]
 [10  0  4  0  0]
 [ 0  0  0 28  3]
 [ 9  0  1 17 10]]

Test set: Average loss: 1.5238, Accuracy: 67/128 (52%)



  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/8 [00:00<?, ?it/s]

[[ 28  10  17   1  21]
 [  0  50   6   0  24]
 [  0   2  70   0  15]
 [  0   0   0 121  15]
 [  0   2  20  40  70]]

Test set: Average loss: 0.7799, Accuracy: 339/512 (66%)



  0%|          | 0/2 [00:00<?, ?it/s]

[[ 7  4  8  0  7]
 [ 0  8  6  0  6]
 [ 0  0 10  0  4]
 [ 0  0  0 26  5]
 [ 2  1  1 16 17]]

Test set: Average loss: 1.0337, Accuracy: 68/128 (53%)



  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/8 [00:00<?, ?it/s]

[[76  0  1  0  0]
 [42 38  0  0  0]
 [66  1 17  0  3]
 [41  0  0 92  3]
 [69 13  3 31 16]]

Test set: Average loss: 2.3664, Accuracy: 239/512 (47%)



  0%|          | 0/2 [00:00<?, ?it/s]

[[25  0  0  0  1]
 [ 9 11  0  0  0]
 [11  0  2  0  1]
 [ 5  0  0 25  1]
 [19  2  0 11  5]]

Test set: Average loss: 2.0734, Accuracy: 68/128 (53%)



  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/8 [00:00<?, ?it/s]

[[ 23  43   0   0  11]
 [  0  77   0   0   3]
 [  0  51  32   0   4]
 [  1   2   0 133   0]
 [  1  32   8  49  42]]

Test set: Average loss: 0.8851, Accuracy: 307/512 (60%)



  0%|          | 0/2 [00:00<?, ?it/s]

[[ 6 16  0  0  4]
 [ 0 19  0  0  1]
 [ 0  7  6  0  1]
 [ 0  1  0 30  0]
 [ 0  5  0 17 15]]

Test set: Average loss: 0.9526, Accuracy: 76/128 (59%)



  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/8 [00:00<?, ?it/s]

[[ 71   1   2   0   3]
 [  5  69   0   0   6]
 [ 10   0  73   0   4]
 [  0   0   0 130   6]
 [ 14   4   7  47  60]]

Test set: Average loss: 0.5520, Accuracy: 403/512 (79%)



  0%|          | 0/2 [00:00<?, ?it/s]

[[21  2  1  0  2]
 [ 5 11  1  0  3]
 [ 2  0 10  0  2]
 [ 0  0  0 29  2]
 [ 2  1  1 16 17]]

Test set: Average loss: 0.7642, Accuracy: 88/128 (69%)



  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/8 [00:00<?, ?it/s]

[[ 37  32   3   0   5]
 [  0  79   1   0   0]
 [  0  16  63   0   8]
 [  1   0   0 132   3]
 [  0  19  11  46  56]]

Test set: Average loss: 0.6860, Accuracy: 367/512 (72%)



  0%|          | 0/2 [00:00<?, ?it/s]

[[ 6 15  2  0  3]
 [ 0 19  1  0  0]
 [ 0  2  9  0  3]
 [ 0  0  0 30  1]
 [ 0  4  1 17 15]]

Test set: Average loss: 0.9007, Accuracy: 79/128 (62%)



  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/8 [00:00<?, ?it/s]

[[ 72   0   4   0   1]
 [ 48  16   7   0   9]
 [ 14   0  65   0   8]
 [  2   0   4   8 122]
 [ 23   0   9   1  99]]

Test set: Average loss: 1.0178, Accuracy: 260/512 (51%)



  0%|          | 0/2 [00:00<?, ?it/s]

[[22  0  2  0  2]
 [ 9  2  4  0  5]
 [ 1  0  9  0  4]
 [ 0  0  0  1 30]
 [ 3  0  1  0 33]]

Test set: Average loss: 1.1831, Accuracy: 67/128 (52%)



  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/8 [00:00<?, ?it/s]

[[ 50   1  10   2  14]
 [  0  64   6   0  10]
 [  0   1  85   0   1]
 [  0   0   0 136   0]
 [  1   3  12  52  64]]

Test set: Average loss: 0.5628, Accuracy: 399/512 (78%)



  0%|          | 0/2 [00:00<?, ?it/s]

[[11  1  6  0  8]
 [ 0 10  2  0  8]
 [ 0  0 13  0  1]
 [ 0  0  0 31  0]
 [ 1  0  1 17 18]]

Test set: Average loss: 0.8650, Accuracy: 83/128 (65%)



  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/8 [00:00<?, ?it/s]

[[ 64   2   3   1   7]
 [ 21  41   1   0  17]
 [ 11   0  59   0  17]
 [  0   0   0 133   3]
 [  8   2   9  48  65]]

Test set: Average loss: 0.6700, Accuracy: 362/512 (71%)



  0%|          | 0/2 [00:00<?, ?it/s]

[[16  2  3  0  5]
 [ 3  5  3  0  9]
 [ 2  0  7  0  5]
 [ 0  0  0 30  1]
 [ 1  1  1 17 17]]

Test set: Average loss: 0.8428, Accuracy: 75/128 (59%)



  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/8 [00:00<?, ?it/s]

[[ 61   0   4   1  11]
 [  7  28  10   0  35]
 [  5   0  59   0  23]
 [  0   0   0 124  12]
 [  4   1   9  41  77]]

Test set: Average loss: 0.7868, Accuracy: 349/512 (68%)



  0%|          | 0/2 [00:00<?, ?it/s]

[[15  1  4  0  6]
 [ 2  4  3  0 11]
 [ 1  0  8  0  5]
 [ 0  0  0 28  3]
 [ 2  1  1 16 17]]

Test set: Average loss: 0.9685, Accuracy: 72/128 (56%)



  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/8 [00:00<?, ?it/s]

[[ 66   0   5   1   5]
 [ 15  42   4   0  19]
 [ 12   0  54   0  21]
 [  0   0   0 136   0]
 [ 11   3   8  51  59]]

Test set: Average loss: 0.7114, Accuracy: 357/512 (70%)



  0%|          | 0/2 [00:00<?, ?it/s]

[[19  0  4  0  3]
 [ 6  5  2  0  7]
 [ 2  0  7  0  5]
 [ 0  0  0 30  1]
 [ 3  1  0 17 16]]

Test set: Average loss: 0.9287, Accuracy: 77/128 (60%)



  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/8 [00:00<?, ?it/s]

[[ 75   2   0   0   0]
 [ 35  45   0   0   0]
 [ 72  12   2   0   1]
 [ 19   1   0 113   3]
 [ 47  12   2  45  26]]

Test set: Average loss: 1.9317, Accuracy: 261/512 (51%)



  0%|          | 0/2 [00:00<?, ?it/s]

[[26  0  0  0  0]
 [10 10  0  0  0]
 [11  2  0  0  1]
 [ 2  0  0 26  3]
 [ 9  2  0 16 10]]

Test set: Average loss: 1.6502, Accuracy: 72/128 (56%)



  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/8 [00:00<?, ?it/s]

[[ 56   0   9   1  11]
 [ 13  43  11   0  13]
 [  4   0  79   0   4]
 [  1   0   0 135   0]
 [  6   0  13  51  62]]

Test set: Average loss: 0.6811, Accuracy: 375/512 (73%)



  0%|          | 0/2 [00:00<?, ?it/s]

[[16  1  3  0  6]
 [ 1  9  5  0  5]
 [ 2  0 11  0  1]
 [ 0  0  0 31  0]
 [ 1  1  1 17 17]]

Test set: Average loss: 0.9968, Accuracy: 84/128 (66%)



  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/8 [00:00<?, ?it/s]

[[ 75   0   1   1   0]
 [ 24  39   8   0   9]
 [ 41   0  37   0   9]
 [  0   0   0 132   4]
 [ 32  11   7  49  33]]

Test set: Average loss: 1.0715, Accuracy: 316/512 (62%)



  0%|          | 0/2 [00:00<?, ?it/s]

[[25  0  0  0  1]
 [ 8  8  2  0  2]
 [ 7  0  6  0  1]
 [ 0  0  0 29  2]
 [ 7  3  2 17  8]]

Test set: Average loss: 1.1095, Accuracy: 76/128 (59%)



  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/8 [00:00<?, ?it/s]

[[ 71   3   1   0   2]
 [  7  70   0   0   3]
 [  6  21  53   0   7]
 [  1   0   0 135   0]
 [  8  10   7  52  55]]

Test set: Average loss: 0.6248, Accuracy: 384/512 (75%)



  0%|          | 0/2 [00:00<?, ?it/s]

[[21  2  1  0  2]
 [ 2 16  0  0  2]
 [ 4  2  5  0  3]
 [ 0  0  0 31  0]
 [ 2  3  1 17 14]]

Test set: Average loss: 0.8239, Accuracy: 87/128 (68%)



  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/8 [00:00<?, ?it/s]

[[ 76   0   0   1   0]
 [ 28  51   1   0   0]
 [  6   0  78   0   3]
 [  0   0   0 136   0]
 [ 18   1  11  52  50]]

Test set: Average loss: 0.5600, Accuracy: 391/512 (76%)



  0%|          | 0/2 [00:00<?, ?it/s]

[[23  1  0  0  2]
 [ 9  9  2  0  0]
 [ 2  0 12  0  0]
 [ 0  0  0 31  0]
 [ 4  2  1 17 13]]

Test set: Average loss: 0.7828, Accuracy: 88/128 (69%)



  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/8 [00:00<?, ?it/s]

[[ 17  34  11   2  13]
 [  0  80   0   0   0]
 [  0   5  82   0   0]
 [  0   0   0 136   0]
 [  0  22  15  51  44]]

Test set: Average loss: 0.7031, Accuracy: 359/512 (70%)



  0%|          | 0/2 [00:00<?, ?it/s]

[[ 4 12  6  0  4]
 [ 0 19  0  0  1]
 [ 0  0 14  0  0]
 [ 0  0  0 31  0]
 [ 0  5  1 17 14]]

Test set: Average loss: 1.0762, Accuracy: 82/128 (64%)



  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/8 [00:00<?, ?it/s]

[[ 48   0  21   1   7]
 [  4  30  16   0  30]
 [  1   0  83   0   3]
 [  0   0   0 109  27]
 [  3   0  19  32  78]]

Test set: Average loss: 0.7128, Accuracy: 348/512 (68%)



  0%|          | 0/2 [00:00<?, ?it/s]

[[13  1  8  0  4]
 [ 0  4  9  0  7]
 [ 0  0 14  0  0]
 [ 0  0  0 22  9]
 [ 2  1  2 11 21]]

Test set: Average loss: 1.0369, Accuracy: 74/128 (58%)



  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/8 [00:00<?, ?it/s]

[[ 29  24  13   0  11]
 [  0  76   1   0   3]
 [  0   4  78   0   5]
 [  0   0   0 120  16]
 [  0  18  11  34  69]]

Test set: Average loss: 0.6900, Accuracy: 372/512 (73%)



  0%|          | 0/2 [00:00<?, ?it/s]

[[ 5 10  5  0  6]
 [ 0 16  2  0  2]
 [ 0  0 13  0  1]
 [ 0  0  0 23  8]
 [ 1  4  1 13 18]]

Test set: Average loss: 1.0596, Accuracy: 75/128 (59%)



  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/8 [00:00<?, ?it/s]

[[ 57  10   5   0   5]
 [  4  75   0   0   1]
 [  2   5  70   0  10]
 [  2   0   1 133   0]
 [  2  14   7  48  61]]

Test set: Average loss: 0.5694, Accuracy: 396/512 (77%)



  0%|          | 0/2 [00:00<?, ?it/s]

[[15  6  2  0  3]
 [ 1 15  0  0  4]
 [ 2  0 10  0  2]
 [ 0  0  1 30  0]
 [ 0  4  0 17 16]]

Test set: Average loss: 0.7664, Accuracy: 86/128 (67%)



  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/8 [00:00<?, ?it/s]

[[ 63  11   1   0   2]
 [  2  75   0   0   3]
 [  6  24  35   0  22]
 [  0   0   0 128   8]
 [  8  18   3  41  62]]

Test set: Average loss: 0.7105, Accuracy: 363/512 (71%)



  0%|          | 0/2 [00:00<?, ?it/s]

[[15  6  1  0  4]
 [ 1 17  0  0  2]
 [ 3  2  3  0  6]
 [ 0  0  0 25  6]
 [ 1  4  1 13 18]]

Test set: Average loss: 0.9503, Accuracy: 78/128 (61%)



  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/8 [00:00<?, ?it/s]

[[ 74   0   2   0   1]
 [  7  69   3   0   1]
 [  7   2  75   0   3]
 [  1   0   0 135   0]
 [ 12   5   6  51  58]]

Test set: Average loss: 0.4853, Accuracy: 411/512 (80%)



  0%|          | 0/2 [00:00<?, ?it/s]

[[18  3  2  0  3]
 [ 3 11  2  0  4]
 [ 2  0 11  0  1]
 [ 0  0  0 31  0]
 [ 2  1  1 17 16]]

Test set: Average loss: 0.7059, Accuracy: 87/128 (68%)



  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/8 [00:00<?, ?it/s]

[[ 15  30  11   1  20]
 [  5  73   1   0   1]
 [  0   6  75   0   6]
 [  3   0   0 132   1]
 [  1  11  11  47  62]]

Test set: Average loss: 0.8398, Accuracy: 357/512 (70%)



  0%|          | 0/2 [00:00<?, ?it/s]

[[ 6 10  3  0  7]
 [ 1 14  3  0  2]
 [ 0  0 12  0  2]
 [ 1  0  0 29  1]
 [ 0  4  1 17 15]]

Test set: Average loss: 1.1820, Accuracy: 76/128 (59%)



  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/8 [00:00<?, ?it/s]

[[ 63   0   1   0  13]
 [  5  55   1   0  19]
 [  1   1  70   0  15]
 [  2   0   0 134   0]
 [  2   0   5  50  75]]

Test set: Average loss: 0.5765, Accuracy: 397/512 (78%)



  0%|          | 0/2 [00:00<?, ?it/s]

[[12  1  3  0 10]
 [ 2  8  1  0  9]
 [ 0  1  7  0  6]
 [ 1  0  0 30  0]
 [ 0  1  0 17 19]]

Test set: Average loss: 1.0421, Accuracy: 76/128 (59%)



  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/8 [00:00<?, ?it/s]

[[ 58   3   7   1   8]
 [  3  76   1   0   0]
 [  0   2  85   0   0]
 [  0   0   0 136   0]
 [  5   9  15  50  53]]

Test set: Average loss: 0.4852, Accuracy: 408/512 (80%)



  0%|          | 0/2 [00:00<?, ?it/s]

[[15  3  5  0  3]
 [ 0 18  2  0  0]
 [ 0  0 12  0  2]
 [ 0  0  0 31  0]
 [ 2  5  3 17 10]]

Test set: Average loss: 0.7939, Accuracy: 86/128 (67%)



  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/8 [00:00<?, ?it/s]

[[ 52   0   8   0  17]
 [  4  13  37   0  26]
 [  3   0  66   0  18]
 [  0   0   0  13 123]
 [  2   0  20   0 110]]

Test set: Average loss: 1.2961, Accuracy: 254/512 (50%)



  0%|          | 0/2 [00:00<?, ?it/s]

[[13  0  7  0  6]
 [ 1  2  9  0  8]
 [ 2  0  8  0  4]
 [ 0  0  0  2 29]
 [ 1  0  5  0 31]]

Test set: Average loss: 1.4123, Accuracy: 56/128 (44%)



  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/8 [00:00<?, ?it/s]

[[ 43   9  19   1   5]
 [  1  76   2   0   1]
 [  0   0  87   0   0]
 [  0   0   0 134   2]
 [  1  11  20  48  52]]

Test set: Average loss: 0.6177, Accuracy: 392/512 (77%)



  0%|          | 0/2 [00:00<?, ?it/s]

[[11  5  7  0  3]
 [ 0 14  5  0  1]
 [ 0  0 14  0  0]
 [ 0  0  0 29  2]
 [ 0  4  1 17 15]]

Test set: Average loss: 0.8314, Accuracy: 83/128 (65%)



  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/8 [00:00<?, ?it/s]

[[ 70   0   1   2   4]
 [ 14  30   3   0  33]
 [ 14   2  54   0  17]
 [  0   0   0 132   4]
 [ 14   2   7  47  62]]

Test set: Average loss: 0.7234, Accuracy: 348/512 (68%)



  0%|          | 0/2 [00:00<?, ?it/s]

[[22  0  0  0  4]
 [ 2  7  1  0 10]
 [ 2  0 11  0  1]
 [ 0  0  0 28  3]
 [ 2  0  1 16 18]]

Test set: Average loss: 0.8317, Accuracy: 86/128 (67%)



  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/8 [00:00<?, ?it/s]

[[ 71   1   0   0   5]
 [ 33  43   0   0   4]
 [ 61   0  15   0  11]
 [  9   0   0 127   0]
 [ 28   3   5  48  48]]

Test set: Average loss: 1.5383, Accuracy: 304/512 (59%)



  0%|          | 0/2 [00:00<?, ?it/s]

[[22  1  0  0  3]
 [ 5 11  0  0  4]
 [ 9  0  2  0  3]
 [ 2  0  0 29  0]
 [ 6  1  0 17 13]]

Test set: Average loss: 1.3778, Accuracy: 77/128 (60%)



  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/8 [00:00<?, ?it/s]

[[ 65   1   1   1   9]
 [  9  61   3   0   7]
 [  7   2  74   0   4]
 [  0   0   0 136   0]
 [  7   3  11  52  59]]

Test set: Average loss: 0.5059, Accuracy: 395/512 (77%)



  0%|          | 0/2 [00:00<?, ?it/s]

[[14  2  4  0  6]
 [ 1 13  2  0  4]
 [ 2  0 11  0  1]
 [ 0  0  0 31  0]
 [ 0  3  0 17 17]]

Test set: Average loss: 0.7665, Accuracy: 86/128 (67%)



  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/8 [00:00<?, ?it/s]

[[ 59   0   1   0  17]
 [ 40   7   0   0  33]
 [ 45   0  23   0  19]
 [ 10   0   0 126   0]
 [ 11   0   5  44  72]]

Test set: Average loss: 1.8094, Accuracy: 287/512 (56%)



  0%|          | 0/2 [00:00<?, ?it/s]

[[16  0  2  0  8]
 [ 7  1  0  0 12]
 [ 8  0  4  0  2]
 [ 1  0  0 30  0]
 [ 1  0  0 17 19]]

Test set: Average loss: 1.9308, Accuracy: 70/128 (55%)



  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/8 [00:00<?, ?it/s]

[[ 67   1   0   1   8]
 [  8  64   0   0   8]
 [  9   2  20   0  56]
 [  0   0   0 136   0]
 [  5   5   0  49  73]]

Test set: Average loss: 0.8651, Accuracy: 360/512 (70%)



  0%|          | 0/2 [00:00<?, ?it/s]

[[16  2  0  0  8]
 [ 1 12  0  0  7]
 [ 3  0  1  0 10]
 [ 0  0  0 31  0]
 [ 3  1  0 17 16]]

Test set: Average loss: 1.0372, Accuracy: 76/128 (59%)



  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/8 [00:00<?, ?it/s]

[[ 41  10  14   1  11]
 [  1  73   1   0   5]
 [  1   4  78   0   4]
 [  0   0   0 133   3]
 [  2  10  12  51  57]]

Test set: Average loss: 0.6077, Accuracy: 382/512 (75%)



  0%|          | 0/2 [00:00<?, ?it/s]

[[ 5  7  4  0 10]
 [ 0 16  1  0  3]
 [ 0  1 11  0  2]
 [ 0  0  0 29  2]
 [ 0  5  1 16 15]]

Test set: Average loss: 0.9381, Accuracy: 76/128 (59%)



  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/8 [00:00<?, ?it/s]

[[ 11  39  24   1   2]
 [  0  80   0   0   0]
 [  0   8  79   0   0]
 [  0   0   0 136   0]
 [  0  32  17  51  32]]

Test set: Average loss: 0.9314, Accuracy: 338/512 (66%)



  0%|          | 0/2 [00:00<?, ?it/s]

[[ 4 16  5  0  1]
 [ 0 19  1  0  0]
 [ 0  1 13  0  0]
 [ 0  0  0 31  0]
 [ 0 10  1 17  9]]

Test set: Average loss: 1.3008, Accuracy: 76/128 (59%)



  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/8 [00:00<?, ?it/s]

[[ 70   0   0   0   7]
 [ 15  11  17   0  37]
 [ 44   0  36   0   7]
 [  7   0   0 129   0]
 [ 13   0   5  50  64]]

Test set: Average loss: 1.4050, Accuracy: 310/512 (61%)



  0%|          | 0/2 [00:00<?, ?it/s]

[[20  0  0  0  6]
 [ 7  1  3  0  9]
 [ 8  0  5  0  1]
 [ 1  0  0 30  0]
 [ 2  0  4 17 14]]

Test set: Average loss: 1.5720, Accuracy: 70/128 (55%)



  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/8 [00:00<?, ?it/s]

[[ 72   0   4   0   1]
 [ 10  58   4   0   8]
 [  2   0  83   0   2]
 [  0   0   0 133   3]
 [  7   0   8  43  74]]

Test set: Average loss: 0.4639, Accuracy: 420/512 (82%)



  0%|          | 0/2 [00:00<?, ?it/s]

[[19  1  2  0  4]
 [ 2  8  3  0  7]
 [ 2  0 11  0  1]
 [ 0  0  1 27  3]
 [ 2  1  1 14 19]]

Test set: Average loss: 0.7628, Accuracy: 84/128 (66%)



  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/8 [00:00<?, ?it/s]

[[19 16 34  0  8]
 [ 2 70  5  0  3]
 [ 6  0 80  0  1]
 [ 0  0  0 42 94]
 [ 1  7 27  0 97]]

Test set: Average loss: 0.9067, Accuracy: 308/512 (60%)



  0%|          | 0/2 [00:00<?, ?it/s]

[[ 7  2 15  0  2]
 [ 2 11  4  0  3]
 [ 0  0 13  0  1]
 [ 0  0  0  8 23]
 [ 0  4  4  0 29]]

Test set: Average loss: 1.2059, Accuracy: 68/128 (53%)



  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/8 [00:00<?, ?it/s]

[[ 75   0   1   0   1]
 [  4  75   0   0   1]
 [  7   2  77   0   1]
 [  0   0   0 135   1]
 [ 20  16   5  50  41]]

Test set: Average loss: 0.4544, Accuracy: 403/512 (79%)



  0%|          | 0/2 [00:00<?, ?it/s]

[[22  1  2  0  1]
 [ 1 17  0  0  2]
 [ 3  0 10  0  1]
 [ 0  0  0 30  1]
 [ 2  4  0 16 15]]

Test set: Average loss: 0.7869, Accuracy: 94/128 (73%)



  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/8 [00:00<?, ?it/s]

[[ 55   3   8   2   9]
 [  4  46   3   0  27]
 [  5   1  68   0  13]
 [  0   0   0 135   1]
 [  5   0  13  51  63]]

Test set: Average loss: 0.6205, Accuracy: 367/512 (72%)



  0%|          | 0/2 [00:00<?, ?it/s]

[[15  2  3  0  6]
 [ 1  7  2  0 10]
 [ 1  0 12  0  1]
 [ 0  0  0 29  2]
 [ 1  0  0 16 20]]

Test set: Average loss: 0.9182, Accuracy: 83/128 (65%)



  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/8 [00:00<?, ?it/s]

[[ 64   0   2   0  11]
 [  6  54   1   0  19]
 [  9   0  72   0   6]
 [  0   0   0 133   3]
 [ 10   0   3  42  77]]

Test set: Average loss: 0.4675, Accuracy: 400/512 (78%)



  0%|          | 0/2 [00:00<?, ?it/s]

[[19  1  2  0  4]
 [ 1  6  2  0 11]
 [ 4  0  8  0  2]
 [ 0  0  0 28  3]
 [ 2  2  0 15 18]]

Test set: Average loss: 0.8314, Accuracy: 79/128 (62%)



  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/8 [00:00<?, ?it/s]

[[ 70   0   1   2   4]
 [  6  56   0   0  18]
 [ 11   0  66   0  10]
 [  0   0   0 136   0]
 [  9   0   4  52  67]]

Test set: Average loss: 0.6168, Accuracy: 395/512 (77%)



  0%|          | 0/2 [00:00<?, ?it/s]

[[18  2  2  0  4]
 [ 2 11  0  0  7]
 [ 4  0  7  0  3]
 [ 0  0  0 31  0]
 [ 2  3  0 17 15]]

Test set: Average loss: 1.0020, Accuracy: 82/128 (64%)



  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/8 [00:00<?, ?it/s]

[[ 44   1  28   1   3]
 [  0  39  14   0  27]
 [  0   0  80   0   7]
 [  0   0   0 113  23]
 [  1   0  19  24  88]]

Test set: Average loss: 0.7013, Accuracy: 364/512 (71%)



  0%|          | 0/2 [00:00<?, ?it/s]

[[ 7  2 11  0  6]
 [ 0  4  6  0 10]
 [ 0  0 12  0  2]
 [ 0  0  0 24  7]
 [ 2  1  2  7 25]]

Test set: Average loss: 1.2416, Accuracy: 72/128 (56%)



  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/8 [00:00<?, ?it/s]

[[ 69   5   1   0   2]
 [  2  78   0   0   0]
 [  5   7  69   0   6]
 [  1   0   0 133   2]
 [  8  18   9  48  49]]

Test set: Average loss: 0.5179, Accuracy: 398/512 (78%)



  0%|          | 0/2 [00:00<?, ?it/s]

[[18  6  1  0  1]
 [ 0 19  1  0  0]
 [ 4  1  7  0  2]
 [ 0  0  0 29  2]
 [ 4  5  0 15 13]]

Test set: Average loss: 0.7919, Accuracy: 86/128 (67%)



  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/8 [00:00<?, ?it/s]

[[ 40   0   7   2  28]
 [ 33  13   1   0  33]
 [ 18   0  32   0  37]
 [  0   0   0 131   5]
 [  3   0   7  45  77]]

Test set: Average loss: 1.3368, Accuracy: 293/512 (57%)



  0%|          | 0/2 [00:00<?, ?it/s]

[[12  0  1  0 13]
 [ 5  3  0  0 12]
 [ 4  0  4  0  6]
 [ 0  0  0 29  2]
 [ 0  0  0 16 21]]

Test set: Average loss: 1.6268, Accuracy: 69/128 (54%)



  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/8 [00:00<?, ?it/s]

[[ 76   0   0   0   1]
 [ 14  59   0   0   7]
 [ 25   2  39   0  21]
 [  1   0   0 135   0]
 [  9   2   3  51  67]]

Test set: Average loss: 0.7402, Accuracy: 376/512 (73%)



  0%|          | 0/2 [00:00<?, ?it/s]

[[21  1  1  0  3]
 [ 2 10  0  0  8]
 [ 5  1  3  0  5]
 [ 0  0  0 31  0]
 [ 2  1  0 17 17]]

Test set: Average loss: 1.0129, Accuracy: 82/128 (64%)



  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/8 [00:00<?, ?it/s]

[[ 77   0   0   0   0]
 [ 15  65   0   0   0]
 [  7   0  80   0   0]
 [  0   0   0 115  21]
 [ 19   2   6  19  86]]

Test set: Average loss: 0.4174, Accuracy: 423/512 (83%)



  0%|          | 0/2 [00:00<?, ?it/s]

[[23  1  1  0  1]
 [ 6 13  0  0  1]
 [ 3  0 11  0  0]
 [ 0  0  0 23  8]
 [ 4  3  0  6 24]]

Test set: Average loss: 0.7849, Accuracy: 94/128 (73%)



  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/8 [00:00<?, ?it/s]

[[ 76   0   1   0   0]
 [  4  74   1   0   1]
 [  6   1  80   0   0]
 [  0   0   0 133   3]
 [ 11   2   6  39  74]]

Test set: Average loss: 0.3389, Accuracy: 437/512 (85%)



  0%|          | 0/2 [00:00<?, ?it/s]

[[19  1  4  0  2]
 [ 1 15  2  0  2]
 [ 3  0 10  0  1]
 [ 0  0  0 28  3]
 [ 2  3  1 14 17]]

Test set: Average loss: 0.7153, Accuracy: 89/128 (70%)



  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/8 [00:00<?, ?it/s]

[[ 71   0   1   1   4]
 [  2  56   0   0  22]
 [  1   2  67   0  17]
 [  0   0   0 136   0]
 [  1   2   3  51  75]]

Test set: Average loss: 0.4934, Accuracy: 405/512 (79%)



  0%|          | 0/2 [00:00<?, ?it/s]

[[17  3  0  0  6]
 [ 1  8  0  0 11]
 [ 1  0  7  0  6]
 [ 0  0  0 31  0]
 [ 0  1  0 17 19]]

Test set: Average loss: 0.9256, Accuracy: 82/128 (64%)



  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/8 [00:00<?, ?it/s]

[[ 71   2   2   0   2]
 [  0  79   0   0   1]
 [  0   2  81   0   4]
 [  2   0   0 110  24]
 [  0   4   6  16 106]]

Test set: Average loss: 0.3341, Accuracy: 447/512 (87%)



  0%|          | 0/2 [00:00<?, ?it/s]

[[13  8  2  0  3]
 [ 0 17  1  0  2]
 [ 1  1 10  0  2]
 [ 0  0  0 24  7]
 [ 1  4  0  6 26]]

Test set: Average loss: 0.7466, Accuracy: 90/128 (70%)



  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/8 [00:00<?, ?it/s]

[[ 65   1  10   0   1]
 [  7  59   9   0   5]
 [  0   0  87   0   0]
 [  0   0   0 113  23]
 [  4   2  24  10  92]]

Test set: Average loss: 0.4679, Accuracy: 416/512 (81%)



  0%|          | 0/2 [00:00<?, ?it/s]

[[14  1 11  0  0]
 [ 0 13  7  0  0]
 [ 0  0 14  0  0]
 [ 0  0  0 20 11]
 [ 2  2  3  2 28]]

Test set: Average loss: 0.8735, Accuracy: 89/128 (70%)



  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/8 [00:00<?, ?it/s]

[[ 74   0   2   0   1]
 [  5  74   1   0   0]
 [ 10   0  75   0   2]
 [  2   0   0 134   0]
 [  7   9  10  51  55]]

Test set: Average loss: 0.6205, Accuracy: 412/512 (80%)



  0%|          | 0/2 [00:00<?, ?it/s]

[[20  2  2  0  2]
 [ 1 15  4  0  0]
 [ 2  0 10  0  2]
 [ 0  0  0 31  0]
 [ 1  4  1 17 14]]

Test set: Average loss: 1.0010, Accuracy: 90/128 (70%)



  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/8 [00:00<?, ?it/s]

[[ 74   3   0   0   0]
 [  1  79   0   0   0]
 [  1   9  77   0   0]
 [  0   0   0 133   3]
 [ 18  32   9  30  43]]

Test set: Average loss: 0.5850, Accuracy: 406/512 (79%)



  0%|          | 0/2 [00:00<?, ?it/s]

[[18  7  1  0  0]
 [ 0 20  0  0  0]
 [ 3  0 11  0  0]
 [ 0  0  0 28  3]
 [ 5  8  0 11 13]]

Test set: Average loss: 0.8764, Accuracy: 90/128 (70%)



  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/8 [00:00<?, ?it/s]

[[ 73   0   3   0   1]
 [  9  58   8   0   5]
 [  3   0  84   0   0]
 [  0   0   0 136   0]
 [  5   0  14  51  62]]

Test set: Average loss: 0.4514, Accuracy: 413/512 (81%)



  0%|          | 0/2 [00:00<?, ?it/s]

[[16  1  6  0  3]
 [ 1 11  7  0  1]
 [ 3  0 11  0  0]
 [ 0  0  0 31  0]
 [ 2  2  1 17 15]]

Test set: Average loss: 0.9486, Accuracy: 84/128 (66%)



  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/8 [00:00<?, ?it/s]

[[ 29   5  22   0  21]
 [  2  65   9   0   4]
 [  0   0  84   0   3]
 [ 11   0   0 121   4]
 [  6   4  18  37  67]]

Test set: Average loss: 0.8219, Accuracy: 366/512 (71%)



  0%|          | 0/2 [00:00<?, ?it/s]

[[ 8  1 11  0  6]
 [ 2 12  4  0  2]
 [ 0  0 12  0  2]
 [ 1  0  0 27  3]
 [ 1  3  1 13 19]]

Test set: Average loss: 1.3772, Accuracy: 78/128 (61%)



  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/8 [00:00<?, ?it/s]

[[ 76   0   1   0   0]
 [  7  72   1   0   0]
 [ 16   2  63   0   6]
 [  3   0   0 112  21]
 [ 17   7   4  25  79]]

Test set: Average loss: 0.5007, Accuracy: 402/512 (79%)



  0%|          | 0/2 [00:00<?, ?it/s]

[[23  2  0  0  1]
 [ 4 13  2  0  1]
 [ 3  0  8  0  3]
 [ 0  0  0 23  8]
 [ 6  3  0  8 20]]

Test set: Average loss: 0.7852, Accuracy: 87/128 (68%)



  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/8 [00:00<?, ?it/s]

[[ 63   0   6   0   8]
 [  0  70   1   0   9]
 [  0   0  87   0   0]
 [  2   0   0  90  44]
 [  0   0   4   0 128]]

Test set: Average loss: 0.3823, Accuracy: 438/512 (86%)



  0%|          | 0/2 [00:00<?, ?it/s]

[[11  1  7  0  7]
 [ 0 15  2  0  3]
 [ 0  0 13  0  1]
 [ 0  0  0 19 12]
 [ 0  2  0  1 34]]

Test set: Average loss: 0.9395, Accuracy: 92/128 (72%)



  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/8 [00:00<?, ?it/s]

[[ 72   0   5   0   0]
 [  0  79   1   0   0]
 [  0   1  86   0   0]
 [  0   0   0 135   1]
 [  3  10  23  36  60]]

Test set: Average loss: 0.3940, Accuracy: 432/512 (84%)



  0%|          | 0/2 [00:00<?, ?it/s]

[[15  3  7  0  1]
 [ 0 18  2  0  0]
 [ 0  0 14  0  0]
 [ 0  0  0 28  3]
 [ 3  4  2 12 16]]

Test set: Average loss: 0.8258, Accuracy: 91/128 (71%)



  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/8 [00:00<?, ?it/s]

[[56 12  7  0  2]
 [ 0 79  1  0  0]
 [ 0  4 83  0  0]
 [ 0  0  0 88 48]
 [ 0 24 19  8 81]]

Test set: Average loss: 0.5510, Accuracy: 387/512 (76%)



  0%|          | 0/2 [00:00<?, ?it/s]

[[11  6  7  0  2]
 [ 0 17  3  0  0]
 [ 0  2 10  0  2]
 [ 0  0  0 16 15]
 [ 1  6  3  3 24]]

Test set: Average loss: 0.9887, Accuracy: 78/128 (61%)



  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/8 [00:00<?, ?it/s]

[[ 76   0   1   0   0]
 [ 15  65   0   0   0]
 [ 38   7  30   0  12]
 [  2   0   0 133   1]
 [ 20   5   1  49  57]]

Test set: Average loss: 0.8952, Accuracy: 361/512 (71%)



  0%|          | 0/2 [00:00<?, ?it/s]

[[24  1  0  0  1]
 [ 2 16  0  0  2]
 [ 9  0  2  0  3]
 [ 0  0  0 30  1]
 [ 4  1  0 15 17]]

Test set: Average loss: 1.0225, Accuracy: 89/128 (70%)



  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/8 [00:00<?, ?it/s]

[[ 74   3   0   0   0]
 [  3  77   0   0   0]
 [ 11  11  62   0   3]
 [  0   0   0 132   4]
 [ 13  18   2  22  77]]

Test set: Average loss: 0.4801, Accuracy: 422/512 (82%)



  0%|          | 0/2 [00:00<?, ?it/s]

[[20  4  1  0  1]
 [ 1 19  0  0  0]
 [ 4  1  7  0  2]
 [ 0  0  0 29  2]
 [ 3  5  0 11 18]]

Test set: Average loss: 0.7959, Accuracy: 93/128 (73%)



  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/8 [00:00<?, ?it/s]

[[ 71   0   4   0   2]
 [ 13  32  19   0  16]
 [  6   0  67   0  14]
 [  3   0   0 130   3]
 [ 10   0  13  35  74]]

Test set: Average loss: 0.6455, Accuracy: 374/512 (73%)



  0%|          | 0/2 [00:00<?, ?it/s]

[[17  1  5  0  3]
 [ 3  6  5  0  6]
 [ 2  0  9  0  3]
 [ 0  0  0 28  3]
 [ 3  0  2 14 18]]

Test set: Average loss: 0.9779, Accuracy: 78/128 (61%)



  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/8 [00:00<?, ?it/s]

[[ 71   0   1   0   5]
 [  0  74   0   0   6]
 [  0   0  85   0   2]
 [  0   0   0  91  45]
 [  1   1   2   0 128]]

Test set: Average loss: 0.3139, Accuracy: 449/512 (88%)



  0%|          | 0/2 [00:00<?, ?it/s]

[[13  5  3  0  5]
 [ 0 17  0  0  3]
 [ 1  0  8  0  5]
 [ 0  0  1 18 12]
 [ 1  3  0  0 33]]

Test set: Average loss: 0.7341, Accuracy: 89/128 (70%)



  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/8 [00:00<?, ?it/s]

[[ 69   0   0   0   8]
 [ 25   6   0   0  49]
 [ 12   0   4   0  71]
 [  0   0   0   0 136]
 [  9   0   1   0 122]]

Test set: Average loss: 1.9155, Accuracy: 201/512 (39%)



  0%|          | 0/2 [00:00<?, ?it/s]

[[18  0  0  0  8]
 [ 2  1  0  0 17]
 [ 1  0  2  0 11]
 [ 0  0  0  0 31]
 [ 4  0  0  0 33]]

Test set: Average loss: 2.1924, Accuracy: 54/128 (42%)



  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/8 [00:00<?, ?it/s]

[[ 67   1   8   0   1]
 [  0  79   1   0   0]
 [  0   0  87   0   0]
 [  0   0   0  83  53]
 [  2   6  17   0 107]]

Test set: Average loss: 0.3863, Accuracy: 423/512 (83%)



  0%|          | 0/2 [00:00<?, ?it/s]

[[16  1  8  0  1]
 [ 0 15  5  0  0]
 [ 0  0 14  0  0]
 [ 0  0  0 15 16]
 [ 2  4  2  0 29]]

Test set: Average loss: 0.8356, Accuracy: 89/128 (70%)



  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/8 [00:00<?, ?it/s]

[[ 75   0   1   1   0]
 [ 17  62   0   0   1]
 [ 29   2  50   0   6]
 [  0   0   0 136   0]
 [ 28   6   2  52  44]]

Test set: Average loss: 1.0079, Accuracy: 367/512 (72%)



  0%|          | 0/2 [00:00<?, ?it/s]

[[21  1  1  0  3]
 [ 2 14  1  0  3]
 [ 7  0  4  0  3]
 [ 0  0  0 31  0]
 [ 8  3  0 17  9]]

Test set: Average loss: 1.2914, Accuracy: 79/128 (62%)



  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/8 [00:00<?, ?it/s]

[[ 36  20   0   0  21]
 [  0  80   0   0   0]
 [  0   4  65   0  18]
 [  0   0   0  21 115]
 [  1   9   5   0 117]]

Test set: Average loss: 0.7553, Accuracy: 319/512 (62%)



  0%|          | 0/2 [00:00<?, ?it/s]

[[ 7 10  1  0  8]
 [ 0 18  0  0  2]
 [ 0  0  8  0  6]
 [ 0  0  0  3 28]
 [ 0  5  0  0 32]]

Test set: Average loss: 1.2594, Accuracy: 68/128 (53%)



  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/8 [00:00<?, ?it/s]

[[ 62   0  13   1   1]
 [  1  71   5   0   3]
 [  0   0  84   2   1]
 [  0   0   0 136   0]
 [  0   0  10  53  69]]

Test set: Average loss: 0.5001, Accuracy: 422/512 (82%)



  0%|          | 0/2 [00:00<?, ?it/s]

[[10  1 11  1  3]
 [ 0 14  6  0  0]
 [ 1  0 13  0  0]
 [ 0  0  0 31  0]
 [ 1  3  1 17 15]]

Test set: Average loss: 1.0468, Accuracy: 83/128 (65%)



  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/8 [00:00<?, ?it/s]

[[ 68   0   0   0   9]
 [ 11  44   0   0  25]
 [ 11   1  70   0   5]
 [  5   0   0 113  18]
 [  4   0   3   1 124]]

Test set: Average loss: 0.4851, Accuracy: 419/512 (82%)



  0%|          | 0/2 [00:00<?, ?it/s]

[[19  1  2  0  4]
 [ 1  9  1  0  9]
 [ 2  0 11  0  1]
 [ 0  0  0 26  5]
 [ 0  1  0  0 36]]

Test set: Average loss: 0.7520, Accuracy: 101/128 (79%)



  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/8 [00:00<?, ?it/s]

[[ 73   1   0   1   2]
 [ 27  50   1   0   2]
 [ 17   7  59   0   4]
 [  0   2   0 131   3]
 [ 12  11   7  32  70]]

Test set: Average loss: 0.7184, Accuracy: 383/512 (75%)



  0%|          | 0/2 [00:00<?, ?it/s]

[[22  1  1  0  2]
 [ 6 10  0  0  4]
 [ 4  2  7  0  1]
 [ 0  0  0 28  3]
 [ 1  4  0 13 19]]

Test set: Average loss: 0.8168, Accuracy: 86/128 (67%)



  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/8 [00:00<?, ?it/s]

[[ 67   4   1   0   5]
 [  1  79   0   0   0]
 [  0   2  83   0   2]
 [  0   0   0  79  57]
 [  2  10   5   0 115]]

Test set: Average loss: 0.3761, Accuracy: 423/512 (83%)



  0%|          | 0/2 [00:00<?, ?it/s]

[[16  5  2  0  3]
 [ 1 17  0  0  2]
 [ 1  0 11  0  2]
 [ 0  0  0 16 15]
 [ 1  3  1  0 32]]

Test set: Average loss: 0.7106, Accuracy: 92/128 (72%)



  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/8 [00:00<?, ?it/s]

[[ 29   4  26   0  18]
 [  0  69   3   0   8]
 [  0   0  86   0   1]
 [  4   0   0  21 111]
 [  0   0   7   0 125]]

Test set: Average loss: 0.7488, Accuracy: 330/512 (64%)



  0%|          | 0/2 [00:00<?, ?it/s]

[[ 6  5  8  0  7]
 [ 0 16  1  0  3]
 [ 0  0 13  0  1]
 [ 1  0  0  3 27]
 [ 0  1  0  0 36]]

Test set: Average loss: 1.2100, Accuracy: 74/128 (58%)



  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/8 [00:00<?, ?it/s]

[[ 77   0   0   0   0]
 [ 42  36   0   0   2]
 [ 47   0  39   0   1]
 [  0   0   0 134   2]
 [ 26   0   0   7  99]]

Test set: Average loss: 1.0318, Accuracy: 385/512 (75%)



  0%|          | 0/2 [00:00<?, ?it/s]

[[24  1  1  0  0]
 [ 6 12  0  0  2]
 [ 9  0  3  0  2]
 [ 0  0  0 29  2]
 [ 7  0  0  4 26]]

Test set: Average loss: 1.1063, Accuracy: 94/128 (73%)



  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/8 [00:00<?, ?it/s]

[[ 51   1   9   0  16]
 [  3  63   0   0  14]
 [  0   0  84   0   3]
 [  0   0   0 136   0]
 [  0   0   6  25 101]]

Test set: Average loss: 0.3989, Accuracy: 435/512 (85%)



  0%|          | 0/2 [00:00<?, ?it/s]

[[ 8  1  5  0 12]
 [ 1  8  3  0  8]
 [ 0  0 13  0  1]
 [ 0  0  0 31  0]
 [ 0  2  0  8 27]]

Test set: Average loss: 0.8799, Accuracy: 87/128 (68%)



  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/8 [00:00<?, ?it/s]

[[ 74   0   1   0   2]
 [ 21  37   0   0  22]
 [ 28   0  30   0  29]
 [  2   0   0 134   0]
 [  6   0   1  39  86]]

Test set: Average loss: 1.1865, Accuracy: 361/512 (71%)



  0%|          | 0/2 [00:00<?, ?it/s]

[[19  1  1  0  5]
 [ 3  6  0  0 11]
 [ 5  0  2  0  7]
 [ 0  0  0 31  0]
 [ 2  0  0 15 20]]

Test set: Average loss: 1.4060, Accuracy: 78/128 (61%)



  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/8 [00:00<?, ?it/s]

[[ 68   5   0   0   4]
 [  0  80   0   0   0]
 [  0   0  87   0   0]
 [  0   0   0  97  39]
 [  0   8   3   0 121]]

Test set: Average loss: 0.2730, Accuracy: 453/512 (88%)



  0%|          | 0/2 [00:00<?, ?it/s]

[[16  4  2  0  4]
 [ 0 18  0  0  2]
 [ 0  1 11  0  2]
 [ 0  0  0 19 12]
 [ 2  4  0  0 31]]

Test set: Average loss: 0.6849, Accuracy: 95/128 (74%)



  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/8 [00:00<?, ?it/s]

[[ 38   8  24   0   7]
 [  1  77   1   0   1]
 [  0   0  78   0   9]
 [  0   0   0   0 136]
 [  1   4  22   0 105]]

Test set: Average loss: 1.2022, Accuracy: 298/512 (58%)



  0%|          | 0/2 [00:00<?, ?it/s]

[[ 8  3 11  0  4]
 [ 0 13  4  0  3]
 [ 0  0 12  0  2]
 [ 0  0  0  0 31]
 [ 2  4  2  0 29]]

Test set: Average loss: 1.5827, Accuracy: 62/128 (48%)



  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/8 [00:00<?, ?it/s]

[[ 73   1   1   0   2]
 [  2  77   0   0   1]
 [  0   0  87   0   0]
 [  0   0   0 135   1]
 [  4   5   8  20  95]]

Test set: Average loss: 0.2261, Accuracy: 467/512 (91%)



  0%|          | 0/2 [00:00<?, ?it/s]

[[20  3  2  0  1]
 [ 1 14  1  0  4]
 [ 1  0 13  0  0]
 [ 0  0  0 31  0]
 [ 2  4  0  7 24]]

Test set: Average loss: 0.5365, Accuracy: 102/128 (80%)



  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/8 [00:00<?, ?it/s]

[[ 41   0   7   0  29]
 [  1  36  18   0  25]
 [  0   0  78   0   9]
 [  1   0   0 135   0]
 [  0   0  11  18 103]]

Test set: Average loss: 0.6610, Accuracy: 393/512 (77%)



  0%|          | 0/2 [00:00<?, ?it/s]

[[ 7  1  4  0 14]
 [ 0  6  8  0  6]
 [ 0  0 11  0  3]
 [ 0  0  0 31  0]
 [ 0  0  1  8 28]]

Test set: Average loss: 1.2493, Accuracy: 83/128 (65%)



  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/8 [00:00<?, ?it/s]

[[ 73   2   1   0   1]
 [  6  63   0   0  11]
 [  8  23  53   0   3]
 [  3  14   0  95  24]
 [  5   8   1   0 118]]

Test set: Average loss: 0.6319, Accuracy: 402/512 (79%)



  0%|          | 0/2 [00:00<?, ?it/s]

[[18  4  1  0  3]
 [ 2 15  0  0  3]
 [ 3  3  5  0  3]
 [ 1  1  0 17 12]
 [ 3  2  0  0 32]]

Test set: Average loss: 0.7783, Accuracy: 87/128 (68%)



  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/8 [00:00<?, ?it/s]

[[ 73   1   3   0   0]
 [  6  69   5   0   0]
 [  0   0  87   0   0]
 [  0   0   0 136   0]
 [  5   4  18   7  98]]

Test set: Average loss: 0.2782, Accuracy: 463/512 (90%)



  0%|          | 0/2 [00:00<?, ?it/s]

[[18  1  7  0  0]
 [ 0 11  7  0  2]
 [ 0  0 14  0  0]
 [ 0  0  0 31  0]
 [ 2  3  1  6 25]]

Test set: Average loss: 0.7389, Accuracy: 99/128 (77%)



  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/8 [00:00<?, ?it/s]

[[ 32   1  43   1   0]
 [  1  36  29   0  14]
 [  0   0  87   0   0]
 [  0   0   0 133   3]
 [  0   0  33  10  89]]

Test set: Average loss: 0.7925, Accuracy: 377/512 (74%)



  0%|          | 0/2 [00:00<?, ?it/s]

[[ 5  1 19  0  1]
 [ 1  4 10  0  5]
 [ 0  0 14  0  0]
 [ 0  0  0 30  1]
 [ 0  0  6  2 29]]

Test set: Average loss: 1.5742, Accuracy: 82/128 (64%)



  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/8 [00:00<?, ?it/s]

[[ 73   1   0   0   3]
 [  1  78   0   0   1]
 [  1   5  77   0   4]
 [  1   0   0 135   0]
 [  1   4   1  24 102]]

Test set: Average loss: 0.2690, Accuracy: 465/512 (91%)



  0%|          | 0/2 [00:00<?, ?it/s]

[[16  3  2  0  5]
 [ 1 15  0  0  4]
 [ 1  2 10  0  1]
 [ 0  0  0 31  0]
 [ 0  2  0 11 24]]

Test set: Average loss: 0.6530, Accuracy: 96/128 (75%)



  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/8 [00:00<?, ?it/s]

[[ 46  11   2   0  18]
 [  0  77   0   0   3]
 [  0   3  76   0   8]
 [  0   0   0 123  13]
 [  0   0   3   0 129]]

Test set: Average loss: 0.3507, Accuracy: 451/512 (88%)



  0%|          | 0/2 [00:00<?, ?it/s]

[[ 7  8  2  0  9]
 [ 0 17  0  0  3]
 [ 0  1  8  0  5]
 [ 0  1  0 26  4]
 [ 0  3  1  0 33]]

Test set: Average loss: 0.9333, Accuracy: 91/128 (71%)



  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/8 [00:00<?, ?it/s]

[[ 75   0   0   0   2]
 [  2  75   0   0   3]
 [  1   0  85   0   1]
 [  0   0   0 136   0]
 [  1   0   2  16 113]]

Test set: Average loss: 0.2015, Accuracy: 484/512 (95%)



  0%|          | 0/2 [00:00<?, ?it/s]

[[20  1  1  0  4]
 [ 0 10  0  0 10]
 [ 1  0 10  0  3]
 [ 0  0  0 31  0]
 [ 0  2  0  9 26]]

Test set: Average loss: 0.6349, Accuracy: 97/128 (76%)



  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/8 [00:00<?, ?it/s]

[[ 76   0   1   0   0]
 [ 33  46   0   0   1]
 [ 21   0  61   0   5]
 [  7   0   0 122   7]
 [  9   0   2   0 121]]

Test set: Average loss: 0.6007, Accuracy: 426/512 (83%)



  0%|          | 0/2 [00:00<?, ?it/s]

[[21  0  0  0  5]
 [ 6 10  0  0  4]
 [ 6  0  8  0  0]
 [ 1  0  0 28  2]
 [ 4  0  1  1 31]]

Test set: Average loss: 0.8283, Accuracy: 98/128 (77%)



  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/8 [00:00<?, ?it/s]

[[ 24  18  23   3   9]
 [  0  78   1   0   1]
 [  0   1  83   0   3]
 [  0   0   0 136   0]
 [  2  13  14  40  63]]

Test set: Average loss: 0.7201, Accuracy: 384/512 (75%)



  0%|          | 0/2 [00:00<?, ?it/s]

[[ 4 11  8  1  2]
 [ 0 15  1  0  4]
 [ 0  0 12  0  2]
 [ 0  0  0 31  0]
 [ 0  3  1 13 20]]

Test set: Average loss: 1.1588, Accuracy: 82/128 (64%)



  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/8 [00:00<?, ?it/s]

[[ 75   1   0   1   0]
 [ 34  45   1   0   0]
 [ 76   0  11   0   0]
 [  0   0   0 136   0]
 [ 41  17   2  41  31]]

Test set: Average loss: 2.5136, Accuracy: 298/512 (58%)



  0%|          | 0/2 [00:00<?, ?it/s]

[[25  0  1  0  0]
 [ 8 11  1  0  0]
 [12  0  2  0  0]
 [ 0  0  0 31  0]
 [12  3  0 15  7]]

Test set: Average loss: 2.1833, Accuracy: 76/128 (59%)



  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/8 [00:00<?, ?it/s]

[[ 28  47   1   0   1]
 [  0  79   0   0   1]
 [  0  36  41   0  10]
 [  1  16   0   0 119]
 [  3  47   7   0  75]]

Test set: Average loss: 2.9179, Accuracy: 223/512 (44%)



  0%|          | 0/2 [00:00<?, ?it/s]

[[ 3 20  1  0  2]
 [ 0 20  0  0  0]
 [ 0  6  6  0  2]
 [ 0  2  0  0 29]
 [ 1 15  0  0 21]]

Test set: Average loss: 2.8666, Accuracy: 50/128 (39%)



  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/8 [00:00<?, ?it/s]

[[ 47  15  13   1   1]
 [  0  80   0   0   0]
 [  2   3  82   0   0]
 [  0   0   0 132   4]
 [  0   5  11   0 116]]

Test set: Average loss: 0.2753, Accuracy: 457/512 (89%)



  0%|          | 0/2 [00:00<?, ?it/s]

[[ 8  9  8  0  1]
 [ 0 18  1  0  1]
 [ 0  0 14  0  0]
 [ 0  0  0 28  3]
 [ 0  4  0  0 33]]

Test set: Average loss: 0.6658, Accuracy: 101/128 (79%)



  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/8 [00:00<?, ?it/s]

[[ 70   1   2   0   4]
 [  0  79   0   0   1]
 [  0   0  87   0   0]
 [  0   0   0 124  12]
 [  0   0   2   0 130]]

Test set: Average loss: 0.1517, Accuracy: 490/512 (96%)



  0%|          | 0/2 [00:00<?, ?it/s]

[[15  4  3  0  4]
 [ 0 18  0  0  2]
 [ 0  0 14  0  0]
 [ 0  0  0 27  4]
 [ 0  3  0  0 34]]

Test set: Average loss: 0.6431, Accuracy: 108/128 (84%)



  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/8 [00:00<?, ?it/s]

[[ 77   0   0   0   0]
 [  0  80   0   0   0]
 [  0   0  87   0   0]
 [  0   0   0 135   1]
 [  0   0   0   0 132]]

Test set: Average loss: 0.0507, Accuracy: 511/512 (100%)



  0%|          | 0/2 [00:00<?, ?it/s]

[[20  1  2  0  3]
 [ 1 16  1  0  2]
 [ 0  0 14  0  0]
 [ 0  0  0 31  0]
 [ 2  2  0  0 33]]

Test set: Average loss: 0.4261, Accuracy: 114/128 (89%)



  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/8 [00:00<?, ?it/s]

[[ 74   0   1   0   2]
 [  0  80   0   0   0]
 [  0   0  86   0   1]
 [  0   0   0 134   2]
 [  0   0   1   0 131]]

Test set: Average loss: 0.0715, Accuracy: 505/512 (99%)



  0%|          | 0/2 [00:00<?, ?it/s]

[[20  1  2  0  3]
 [ 0 15  1  0  4]
 [ 0  0 13  0  1]
 [ 0  0  0 31  0]
 [ 0  3  0  0 34]]

Test set: Average loss: 0.4321, Accuracy: 113/128 (88%)



  0%|          | 0/8 [00:00<?, ?it/s]